Update to SiLK 4.0.0_beta4

diff --git a/silk-src/src/rwflowpack/rwflowpack.init.d.in b/silk-src/src/rwflowpack/rwflowpack.init.d.in
--- a/silk-src/src/rwflowpack/rwflowpack.init.d.in
+++ b/silk-src/src/rwflowpack/rwflowpack.init.d.in
@@ -1,14 +1,23 @@
 #!/bin/sh
 
 #######################################################################
-# RCSIDENT("$SiLK: rwflowpack.init.d.in 02367a659674 2016-05-05 20:17:43Z mthomas $")
+# RCSIDENT("$SiLK: rwflowpack.init.d.in 6de71b57495d 2017-06-23 19:55:24Z mthomas $")
 #######################################################################
 
 # rwflowpack start/control script
 #
 # /etc/init.d/@myprog@
 # chkconfig: - 20 95
-# description: Start @myprog@ program
+# description: SiLK network flow capturing, categorizing, and packing daemon
+# processname: @myprog@
+### BEGIN INIT INFO
+# Provides: @myprog@
+# Required-Start: $local_fs $remote_fs $network $named $syslog $time
+# Required-Stop: $local_fs $remote_fs $network $named $syslog $time
+# Short-Description: start and stop SiLK @myprog@ daemon
+# Description: SiLK daemon to collect network flow data, categorize it by
+#              where it was collected, and store it in SiLK Flow files
+### END INIT INFO
 
 MYNAME=@myprog@
 
@@ -50,7 +59,7 @@ fi
 
 . "${SCRIPT_CONFIG}"
 
-if [ "x$ENABLED" = "x" ] ; then
+if [ "x${PACKER_LUA}" = "x" ] ; then
     exit 0
 fi
 
@@ -94,19 +103,11 @@ check_dir()
 
 #######################################################################
 
-# for backwards compatibility
-if [ "x${BIN_DIR}" = "x" ] ; then
-    #echo "Warning: PACKER_BIN deprecated in ${SCRIPT_CONFIG}.  Use BIN_DIR instead" 1>&2
-    BIN_DIR="${PACKER_BIN}"
-fi
-
-
 RETVAL=0
 
 PROG=@myprog@
 PROG_PATH="${BIN_DIR}/${PROG}"
 PIDFILE="${PID_DIR}/${PROG}${SUFFIX}.pid"
-LOG_BASENAME="${PROG}${SUFFIX}"
 PROG_OPTIONS=""
 
 if [ ! -x "${PROG_PATH}" ] ; then
@@ -114,137 +115,11 @@ if [ ! -x "${PROG_PATH}" ] ; then
     exit 1
 fi
 
-
-check_empty "INPUT_MODE" "${INPUT_MODE}"
-case "${INPUT_MODE}" in
-    stream)
-        check_empty "SENSOR_CONFIG" "${SENSOR_CONFIG}"
-        PROG_OPTIONS="${PROG_OPTIONS} --sensor-configuration='${SENSOR_CONFIG}'"
-        ;;
-    fcfiles)
-        check_empty "SENSOR_CONFIG" "${SENSOR_CONFIG}"
-        PROG_OPTIONS="${PROG_OPTIONS} --input-mode=fcfiles"
-        PROG_OPTIONS="${PROG_OPTIONS} --sensor-configuration='${SENSOR_CONFIG}'"
-        ;;
-    respool)
-        PROG_OPTIONS="${PROG_OPTIONS} --input-mode=respool"
-        ;;
-    *)
-        echo "$0: Unexpected INPUT_MODE ${INPUT_MODE}."
-        echo "Set to \"stream\", \"fcfiles\", or \"respool\"."
-        exit 1
-        ;;
-esac
-
-
-if [ "x${COMPRESSION_TYPE}" != "x" ] ; then
-    PROG_OPTIONS="${PROG_OPTIONS} --compression-method=${COMPRESSION_TYPE}"
+if [ ! -f "${PACKER_LUA}" ] ; then
+    echo "$0: could not find configuration file ${PACKER_LUA}."
+    exit 1
 fi
-if [ "x${FILE_LOCKING}" = "x0" ] ; then
-    PROG_OPTIONS="${PROG_OPTIONS} --no-file-locking"
-fi
-if [ "x${PACK_INTERFACES}" = "x1" ] ; then
-    PROG_OPTIONS="${PROG_OPTIONS} --pack-interfaces"
-fi
-if [ "x${FLUSH_TIMEOUT}" != "x" ] ; then
-    PROG_OPTIONS="${PROG_OPTIONS} --flush-timeout=${FLUSH_TIMEOUT}"
-fi
-if [ "x${FILE_CACHE_SIZE}" != "x" ] ; then
-    PROG_OPTIONS="${PROG_OPTIONS} --file-cache-size=${FILE_CACHE_SIZE}"
-fi
-if [ "x${POLLING_INTERVAL}" != "x" ] ; then
-    PROG_OPTIONS="${PROG_OPTIONS} --polling-interval=${POLLING_INTERVAL}"
-fi
-if [ "x${SITE_CONFIG}" != "x" ] ; then
-    PROG_OPTIONS="${PROG_OPTIONS} --site-config-file='${SITE_CONFIG}'"
-fi
-
-if [ "x${PACKING_LOGIC}" != "x" ] ; then
-    case "${INPUT_MODE}" in
-        respool)
-            ;;
-        *)
-            PROG_OPTIONS="${PROG_OPTIONS} --packing-logic='${PACKING_LOGIC}'"
-            ;;
-    esac
-fi
-
-if [ "x${ARCHIVE_DIR}" != "x" ] ; then
-    check_dir "ARCHIVE_DIR" "${ARCHIVE_DIR}"
-    PROG_OPTIONS="${PROG_OPTIONS} --archive-directory='${ARCHIVE_DIR}'"
-    if [ "x${FLAT_ARCHIVE}" = "x1" ] ; then
-        PROG_OPTIONS="${PROG_OPTIONS} --flat-archive"
-    fi
-fi
-if [ "x${ERROR_DIR}" != "x" ] ; then
-    check_dir "ERROR_DIR" "${ERROR_DIR}"
-    PROG_OPTIONS="${PROG_OPTIONS} --error-directory='${ERROR_DIR}'"
-fi
-
-case "${INPUT_MODE}" in
-    fcfiles|respool)
-        check_dir "INCOMING_DIR" "${INCOMING_DIR}"
-        PROG_OPTIONS="${PROG_OPTIONS} --incoming-directory='${INCOMING_DIR}'"
-        ;;
-    *)
-        ;;
-esac
-
-
-check_empty "OUTPUT_MODE" "${OUTPUT_MODE}"
-case "${OUTPUT_MODE}" in
-    local-storage|local)
-        check_dir "DATA_ROOTDIR" "${DATA_ROOTDIR}"
-        PROG_OPTIONS="${PROG_OPTIONS} --output-mode=local-storage --root-directory='${DATA_ROOTDIR}'"
-        ;;
-    incremental-files)
-        check_dir "INCREMENTAL_DIR" "${INCREMENTAL_DIR}"
-        PROG_OPTIONS="${PROG_OPTIONS} --output-mode=incremental-files --incremental-directory='${INCREMENTAL_DIR}'"
-        ;;
-    remote|sending)
-        check_dir "SENDER_DIR" "${SENDER_DIR}"
-        check_dir "INCREMENTAL_DIR" "${INCREMENTAL_DIR}"
-        PROG_OPTIONS="${PROG_OPTIONS} --output-mode=sending --sender-directory='${SENDER_DIR}' --incremental-directory='${INCREMENTAL_DIR}'"
-        ;;
-    *)
-        echo "$0: Unexpected OUTPUT_MODE ${OUTPUT_MODE}."
-        echo "Set to \"local-storage\" or \"incremental-files\"."
-        exit 1
-        ;;
-esac
-
-# Be certain EXTRA_ENVVAR ends with a space when it is non-empty
-if [ "x${EXTRA_ENVVAR}" != "x" ]; then
-    if [ "x${SILK_IPFIX_PRINT_TEMPLATES}" != "x" ]; then
-        EXTRA_ENVVAR="${EXTRA_ENVVAR} SILK_IPFIX_PRINT_TEMPLATES=${SILK_IPFIX_PRINT_TEMPLATES} "
-    else
-        EXTRA_ENVVAR="${EXTRA_ENVVAR} "
-    fi
-elif [ "x${SILK_IPFIX_PRINT_TEMPLATES}" != "x" ]; then
-    EXTRA_ENVVAR="SILK_IPFIX_PRINT_TEMPLATES=${SILK_IPFIX_PRINT_TEMPLATES} "
-fi
-
-
-
-#######################################################################
-
-check_dir   "PID_DIR"  "${PID_DIR}"
-PROG_OPTIONS="${PROG_OPTIONS} --pidfile='${PIDFILE}' --log-level=${LOG_LEVEL}"
-
-case "${LOG_TYPE}" in
-    syslog)
-        PROG_OPTIONS="${PROG_OPTIONS} --log-destination=syslog"
-        ;;
-    legacy)
-        check_dir "LOG_DIR" "${LOG_DIR}"
-        PROG_OPTIONS="${PROG_OPTIONS} --log-directory='${LOG_DIR}' --log-basename='${LOG_BASENAME}'"
-        ;;
-    *)
-        echo "$0: Unexpected LOG_TYPE ${LOG_TYPE}."
-        echo "Set to \"legacy\" or \"syslog\"."
-        exit 1
-        ;;
-esac
+PROG_OPTIONS="${PACKER_LUA}"
 
 
 #######################################################################
@@ -316,9 +191,9 @@ start() {
     /bin/rm -f ${PIDFILE} 2> /dev/null
 
     if [ X`whoami` = "X${USER}" ] ; then
-        eval "${EXTRA_ENVVAR}${PROG_PATH} ${PROG_OPTIONS} ${EXTRA_OPTIONS} &"
+        eval "${PROG_PATH} ${PROG_OPTIONS} ${EXTRA_OPTIONS} &"
     else
-        su - ${USER} -c "${EXTRA_ENVVAR}${PROG_PATH} ${PROG_OPTIONS} ${EXTRA_OPTIONS} &"
+        su - ${USER} -c "${PROG_PATH} ${PROG_OPTIONS} ${EXTRA_OPTIONS} &"
     fi
     RETVAL=$?
     if [ "$RETVAL" -ne "0" ] ; then
@@ -387,13 +262,18 @@ case "$1" in
     RETVAL=$?
     ;;
 
+  force-reload)
+    (restart)
+    RETVAL=$?
+    ;;
+
   status)
     (status)
     RETVAL=$?
     ;;
 
   *)
-    echo $"Usage: $0 {start|stop|status|restart}"
+    echo $"Usage: $0 {start|stop|status|restart|force-reload}"
     RETVAL=1
     ;;
 esac
@@ -402,7 +282,7 @@ exit $RETVAL
 
 
 #######################################################################
-# @OPENSOURCE_LICENSE_START@
+# @OPENSOURCE_HEADER_START@
 #
 # Use of the SILK system and related source code is subject to the terms
 # of the following licenses:
@@ -448,5 +328,5 @@ exit $RETVAL
 # Government purposes only pursuant to the copyright license under the
 # contract clause at 252.227.7013.
 #
-# @OPENSOURCE_LICENSE_END@
+# @OPENSOURCE_HEADER_END@
 #######################################################################
